set MATLAB=C:\Program Files\MATLAB\R2016a
"C:\PROGRA~1\MATLAB\R2016a\bin\win64\gmake" -f pendulo_fuzzy2015.mk  EXTMODE_STATIC_ALLOC=0 EXTMODE_STATIC_ALLOC_SIZE=1000000 TMW_EXTMODE_TESTING=0 ISPROTECTINGMODEL=NOTPROTECTING OPTS="-DTGTCONN -DON_TARGET_WAIT_FOR_START=1"
